import os
import glob
import time
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm

# Internal Imports
from models.voxelizer import create_structured_latent
from models.architectures import ObjectX_System

# -------------------------------------------------------------------------
# 1. Dedicated Dataset for Your Pre-processed Pairs
# -------------------------------------------------------------------------
class ScanNetppPairsDataset(Dataset):
    def __init__(self, data_dir):
        """Loads the pre-packaged canonical .pt pairs generated by your script."""
        self.data_dir = data_dir
        self.file_paths = glob.glob(os.path.join(data_dir, "*.pt"))
        
        if not self.file_paths:
            raise FileNotFoundError(f"No .pt training pairs found in {data_dir}. Run your generator first!")
            
        print(f"📦 Found {len(self.file_paths)} pre-processed object pairs for training.")

    def __len__(self):
        return len(self.file_paths)

    def __getitem__(self, idx):
        # Load the complete dictionary containing partial scan, features, and GT CAD
        sample = torch.load(self.file_paths[idx], weights_only=False)
        return sample

# -------------------------------------------------------------------------
# 2. Checkpoint Management
# -------------------------------------------------------------------------
def save_checkpoint(model, optimizer, epoch, loss, save_dir):
    os.makedirs(save_dir, exist_ok=True)
    checkpoint_path = os.path.join(save_dir, f"checkpoint_epoch_{epoch:03d}.pth")
    torch.save({
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'loss': loss,
    }, checkpoint_path)
    print(f"💾 Checkpoint saved cleanly to: {checkpoint_path}")

# -------------------------------------------------------------------------
# 3. Main Loop
# -------------------------------------------------------------------------
if __name__ == "__main__":
    print("🚀 Initializing Multi-Scene ObjectX Training Engine...")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    # --- Paths & Hyperparameters ---
    TRAIN_DATA_DIR = "data/geometric_pairs_dataset/train"
    CHECKPOINT_DIR = "checkpoints/objectx_multiscene"
    MAX_HOURS = 5.0
    EPOCHS = 300
    ACCUMULATION_STEPS = 4  # Aggregates gradients over 4 objects to stabilize updates
    
    # --- Infrastructure Setup ---
    dataset = ScanNetppPairsDataset(data_dir=TRAIN_DATA_DIR)
    # Using batch_size=1 because different target items have varying point counts
    dataloader = DataLoader(dataset, batch_size=1, shuffle=True, num_workers=4, pin_memory=True)

    model = ObjectX_System(in_channels=1408).to(device)
    model.train()
    
    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)
    criterion_occ = nn.BCEWithLogitsLoss() 

    # --- Burn-in Session ---
    start_time = time.time()
    
    for epoch in range(EPOCHS):
        epoch_loss = 0.0
        optimizer.zero_grad()
        
        # Wrapped loop in a neat progress bar for interactive tracking
        progress_bar = tqdm(dataloader, desc=f"Epoch {epoch:03d}", leave=False)
        
        for step, batch in enumerate(progress_bar):
            # 1. Extract and cast back to full Float32 for 3D grid safety
            partial_pts = batch['partial_pts'].squeeze(0).float().to(device)
            partial_feats = batch['partial_feats'].squeeze(0).float().to(device)
            gt_pts = batch['gt_pts'].squeeze(0).float().to(device)
            
            # 2. Extract dynamic oracle bounds per individual item
            o_min, o_max = gt_pts.min(dim=0)[0], gt_pts.max(dim=0)[0]
            
            # 3. Voxelize targets & inputs using item-specific bounds
            _, gt_mask = create_structured_latent(gt_pts, torch.zeros_like(gt_pts), o_min, o_max, grid_res=64)
            target_occupancy = gt_mask.float().to(device)
            
            voxel_in, mask_in = create_structured_latent(partial_pts, partial_feats, o_min, o_max, grid_res=64)
            
            # 4. Forward execution
            preds = model(voxel_in, mask_in)
            loss = criterion_occ(preds["occ"], target_occupancy)
            
            # 5. Gradient Scaling & Backward step
            loss = loss / ACCUMULATION_STEPS
            loss.backward()
            
            # 6. Optimize weights after accumulating enough items
            if (step + 1) % ACCUMULATION_STEPS == 0 or (step + 1) == len(dataloader):
                optimizer.step()
                optimizer.zero_grad()
                
            epoch_loss += loss.item() * ACCUMULATION_STEPS
            progress_bar.set_postfix(loss=loss.item() * ACCUMULATION_STEPS)

        # --- Performance Tracking & Time Safety ---
        avg_loss = epoch_loss / len(dataloader)
        elapsed_time = (time.time() - start_time) / 3600
        print(f"✨ [Epoch {epoch:03d}] Finished. Loss: {avg_loss:.6f} | Total Run Time: {elapsed_time:.2f} hrs")
        
        # Periodic saves
        if epoch % 5 == 0 or epoch == EPOCHS - 1:
            save_checkpoint(model, optimizer, epoch, avg_loss, CHECKPOINT_DIR)
            
        # Graceful exit control for the 5-hour cluster constraint
        if elapsed_time >= MAX_HOURS:
            print(f"⏰ Reached limit of {MAX_HOURS} hours. Writing final safe states before exit.")
            save_checkpoint(model, optimizer, epoch, avg_loss, CHECKPOINT_DIR)
            break

    print("🏁 Training routine complete!")